# BetBet Platform — Render Blueprint (fixed)

services:
  # ──────────────────────────────
  # Redis (managed)
  # ──────────────────────────────
  - type: redis
    name: betbet-redis
    plan: free
    ipAllowList: []   # private by default

  # ──────────────────────────────
  # Frontend (Next.js)
  # ──────────────────────────────
  - type: web
    name: betbet-frontend
    env: node
    plan: free
    region: oregon
    buildCommand: |
      cd frontend
      npm ci --legacy-peer-deps
      npm run build
    startCommand: |
      cd frontend
      npm start
    envVars:
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://betbet-api-gateway.onrender.com
      - key: NEXT_PUBLIC_USER_PROFILE_URL
        value: https://betbet-user-profile.onrender.com
      - key: NEXT_PUBLIC_GAME_ENGINE_URL
        value: https://betbet-game-engine.onrender.com
      - key: NEXT_PUBLIC_BETTING_MARKET_URL
        value: https://betbet-betting-market.onrender.com
      - key: NEXT_PUBLIC_WALLET_URL
        value: https://betbet-wallet.onrender.com
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false

  # ──────────────────────────────
  # User Profile Service (FastAPI)
  # ──────────────────────────────
  - type: web
    name: betbet-user-profile
    env: python
    plan: free
    region: oregon
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend/services/user_profile
      PYTHONPATH=../.. uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: betbet-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: betbet-redis
          property: connectionString
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_WEBHOOK_SECRET
        sync: false
      - key: CLERK_DOMAIN
        value: betbet.co.zw
      - key: MONGODB_URL
        sync: false

  # ──────────────────────────────
  # Game Engine (FastAPI)
  # ──────────────────────────────
  - type: web
    name: betbet-game-engine
    env: python
    plan: free
    region: oregon
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend/services/game_engine
      PYTHONPATH=../.. uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: betbet-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: betbet-redis
          property: connectionString
      - key: MONGODB_URL
        sync: false

  # ──────────────────────────────
  # Betting Market (FastAPI)
  # ──────────────────────────────
  - type: web
    name: betbet-betting-market
    env: python
    plan: free
    region: oregon
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend/services/betting_market
      PYTHONPATH=../.. uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: betbet-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: betbet-redis
          property: connectionString
      - key: MONGODB_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false

  # ──────────────────────────────
  # Wallet Service (FastAPI)
  # ──────────────────────────────
  - type: web
    name: betbet-wallet
    env: python
    plan: free
    region: oregon
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend/services/wallet
      PYTHONPATH=../.. uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: betbet-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: betbet-redis
          property: connectionString
      - key: MONGODB_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false

  # ──────────────────────────────
  # Analytics Service (FastAPI)
  # ──────────────────────────────
  - type: web
    name: betbet-analytics
    env: python
    plan: free
    region: oregon
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend/services/analytics
      PYTHONPATH=../.. uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: betbet-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: betbet-redis
          property: connectionString
      - key: MONGODB_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  # ──────────────────────────────
  # Social Forum Service (FastAPI)
  # ──────────────────────────────
  - type: web
    name: betbet-social-forum
    env: python
    plan: free
    region: oregon
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend/services/social_forum
      PYTHONPATH=../.. uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: betbet-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: betbet-redis
          property: connectionString
      - key: MONGODB_URL
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false

# ──────────────────────────────
# PostgreSQL (managed)
# ──────────────────────────────
databases:
  - name: betbet-postgres
    plan: free
    region: oregon
    databaseName: betbet
    user: betbet_user
    ipAllowList: []     # keep it private